INSERT INTO books
  (title,quantity,author_id)
VALUES
  ("ac facilisis facilisis, magna tellus", 5, 10),
  ("nisi. Cum", 7, 10),
  ("a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras", 4, 6),
  ("accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem", 3, 9),
  ("luctus ut, pellentesque eget, dictum placerat, augue. Sed", 3, 9),
  ("Mauris", 9, 5),
  ("Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem,", 3, 1),
  ("tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non", 10, 5),
  ("in", 6, 6),
  ("placerat, orci lacus vestibulum lorem, sit amet ultricies sem", 9, 3),
  ("cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur", 5, 1),
  ("parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida", 9, 5),
  ("ante, iaculis nec, eleifend non, dapibus", 5, 9),
  ("magna sed dui. Fusce aliquam, enim nec tempus scelerisque,", 1, 2),
  ("auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod", 6, 9),
  ("volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida", 2, 4),
  ("libero at", 10, 2),
  ("nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat.", 3, 3),
  ("ultricies ligula. Nullam", 7, 1),
  ("at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed", 5, 3),
  ("eu sem. Pellentesque ut ipsum", 7, 8),
  ("enim. Mauris quis", 1, 4),
  ("facilisis facilisis, magna tellus faucibus leo, in lobortis tellus", 5, 3),
  ("convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus", 6, 5),
  ("elit, pretium et, rutrum non, hendrerit id, ante.", 5, 8),
  ("Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus", 4, 2),
  ("felis eget varius", 3, 1),
  ("nisl arcu iaculis enim, sit amet ornare lectus justo eu", 3, 4),
  ("convallis, ante lectus convallis est, vitae sodales nisi magna sed dui.", 1, 10),
  ("nisi dictum augue malesuada malesuada. Integer id magna et ipsum", 3, 2);